# Site Config
name: "Kelli Ho"
description: Product designer at IBM
baseurl: "/kkh"
url: https://kellular.github.io/kkh

# Build Settings
markdown: kramdown
highlighter: true
permalink: pretty

# In/ Excludes
include: [".htaccess"]
exclude: ["node_modules", "gulpfile.js", "Gemfile", "Gemfile.lock", ".jekyll-metadata", "commit-hook.sh", "package.json", "local_config.yml", "README.md"]

# Read and Output Collections
collections:
  projects:
    output: true
    permalink: projects/:path/
